steps:
- task: Docker@2
  displayName: Build and test testapi image
  inputs:
    containerRegistry: 'tma-acr-connection'
    repository: 'dotnetcore'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile-test'