steps:
- id: build-test-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/nj-mysql-test:test', '--target','test','.']
- id: run-tests
  name: 'gcr.io/nj-mysql-test:test'
  waitFor:
    - build-test-image
- id: build-stage-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/nj-mysql-test:stage', '--target','prod','.']
