steps:
- id: build-test-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nj-mysql-test:$COMMIT_SHA', '--target','test','.']
- id: run-tests
  name: 'gcr.io/$PROJECT_ID/nj-mysql-test:$COMMIT_SHA'
  waitFor:
    - build-test-image