steps:
- id: list wks
  name: 'gcr.io/cloud-builders/curl'
  entrypoint: 'bash'
  args:
  - '-c' # pass what follows as a command to bash
  - |
    ls -la
- id: build-test-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nj-mysql-test:test', '--target','test','.']
- id: run-tests
  name: 'gcr.io/$PROJECT_ID/nj-mysql-test:test'
  waitFor:
    - build-test-image
- id: build-stage-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nj-mysql:$TAG_NAME', '--target','prod','.']
- id: push-stage-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/nj-mysql:$TAG_NAME']
