steps:
- id: list wks
  name: 'gcr.io/cloud-builders/curl'
  entrypoint: 'bash'
  args:
  - '-c' # pass what follows as a command to bash
  - |
    ls -la
-id: Build Helm cloudbuilder image
 name: 'gcr.io/cloud-builders/docker'
 args: ['build', '--tag=gcr.io/$PROJECT_ID/helm', '--build-arg', 'HELM_VERSION=v2.14.0', '.']

images: ['gcr.io/$PROJECT_ID/helm']