FROM node:8-stretch 
# Change working directory
WORKDIR "/app"

# Update packages and install dependency packages for services
RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get clean \
 && echo 'Finished installing dependencies'


# Install npm production packages
COPY package.json /app/
RUN cd /app; npm install

COPY . /app

# Copy the test files
COPY tests tests

ENV NODE_ENV dev
# 1. Get test packages; AND
# 2. Install our test framework - mocha
RUN npm update && npm install -g mocha
# Override the command, to run the test instead of the application
#CMD ["sleep", "100000"]
CMD ["mocha", "tests/test.js", "--reporter", "spec", "--exit"]
