version: '3.3'
services:

  nodejs:
    image: ${DOCKER_USERNAME}/testapi:2.1
    ports:
      - 80:3000
    networks:
      front_net:
        aliases:
          - testapi-service

  maria:
    image:  ${DOCKER_USERNAME}/maria:2.0
    ports:
      - 3306:3306
    networks:
      front_net:
        aliases:
          - mariadb

  prometheus:
    image: ${DOCKER_USERNAME}/prometheus:1.1
    ports:
      - '9090:9090'
    networks:
      front_net:
      back_net:

networks:
  front_net:
  back_net:



