# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Set variables once
variables:
  imageName: dotnetcore

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- script: | 
    docker build -t $(dockerId).azurecr.io/$(imageName):latest .  # add options to this command to meet your needs
    docker login  $(dockerId).azurecr.io -u $(dockerId) -p $(password)
    docker push $(dockerId).azurecr.io/$(imageName)