# Default values for testapi-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

testapi:
  name: testapi
  image:
    repository: gcr.io/PROJECT_ID/testapi
    tag: TAG_NAME
  imagePullPolicy: Always
  replicaCount: 1
  containerPort: 3000

prometheus:
  name: prometheus
  image:
    repository: gcr.io/PROJECT_ID/prometheus
    tag: TAG_NAME
  imagePullPolicy: Always
  replicaCount: 1
  containerPort: 9090