apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 90
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: LoadBalancer

