apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment-{{ .Release.Name }} 
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: tmarkunin/prometheus:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9090